$("header").after("<div id='page_h'></div>");
$("#menu_list").after("<div id='menu_h'></div>");
function windowSize(){
	var box_h = $(window).height() - $("#content").outerHeight() - $("header").outerHeight() - 70;
	var menu_h = $("html").height() - $("#menu_list").outerHeight() - $('#flat-form').outerHeight() - 120;
	if (box_h > 0) {$('#page_h').height(box_h);}
	if (menu_h > 0) {$('#menu_h').height(menu_h);}
}
$(window).on('load resize',windowSize);

$(document).ready(function() {
$('.tabs').on('click','li a',function(e){e.preventDefault();var $tab=$(this),href=$tab.attr('href');$('.active').removeClass('active');$tab.addClass('active');$('.show').removeClass('show').addClass('hide').hide();$(href).removeClass('hide').addClass('show').hide().fadeIn(550)});
(function(a){function b(a,b){(c(a,b)?e:d)(a,b)}var c,d,e;"classList"in document.documentElement?(c=function(a,b){return a.classList.contains(b)},d=function(a,b){a.classList.add(b)},e=function(a,b){a.classList.remove(b)}):(c=function(a,b){return RegExp("(^|\\s+)"+b+"(\\s+|$)").test(a.className)},d=function(a,b){c(a,b)||(a.className=a.className+" "+b)},e=function(a,b){a.className=a.className.replace(RegExp("(^|\\s+)"+b+"(\\s+|$)")," ")});var g={hasClass:c,addClass:d,removeClass:e,toggleClass:b,has:c,
add:d,remove:e,toggle:b};"function"===typeof define&&define.amd?define(g):a.classie=g})(window);
var SidebarMenuEffects=function(){function a(b,d){return b===document?!1:classie.has(b,d)?!0:b.parentNode&&a(b.parentNode,d)}function b(){var a=!1,b=navigator.userAgent||navigator.vendor||window.opera;if(/(android|ipad|playbook|silk|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(b)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(b.substr(0,
4)))a=!0;return a}(function(){var c=document.getElementById("st-container"),d=Array.prototype.slice.call(document.querySelectorAll("#st-trigger-effects")),e=b()?"touchstart":"click",g=function(b){a(b.target,"st-menu")||(classie.remove(c,"st-menu-open"),document.removeEventListener(e,g))};d.forEach(function(a,b){var d=a.getAttribute("data-effect");a.addEventListener(e,function(a){a.stopPropagation();a.preventDefault();c.className="st-container";classie.add(c,d);setTimeout(function(){classie.add(c,
"st-menu-open")},25);document.addEventListener(e,g)})})})()}();
});