language: go

go:
- 1.8

addons:
  apt:
    sources:
    - sourceline: 'ppa:masterminds/glide'
    packages:
    - glide

install:
- make -B vendor

script: make verify

cache:
  directories:
  - ~/.glide
