---
- name: Install zsh
  hosts: all
  sudo: yes

  # vars:
  #   pbname: $inventory_hostname
  #   distro: ${ansible_distribution}
  #   pkg_mgr: ${ansible_pkg_mgr}
  #   zsh_theme: steeef

  tasks:
  - name: Installing Zsh and git
    apt: name={{ item }} state=latest
    with_items:
     - git
     - zsh
     - git-core

  - name: Backing up existing ~/.zshrc
    action: shell if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc{,.orig}; fi

  - name: Cloning oh-my-zsh
    git:
      repo: https://github.com/robbyrussell/oh-my-zsh
      dest: ~/.oh-my-zsh
    register: cloning
    sudo: no

  - name: Creating new ~/.zshrc
    copy:
      src=~/.oh-my-zsh/templates/zshrc.zsh-template
      dest=~/.zshrc
    when: cloning|success
    sudo: no

  - name: Change uoyr shell to zsh
    action: shell chsh -s `which zsh`

  - name: Reboot this server
    shell: reboot
    async: 0
    poll: 0
