{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: {{ template "mongodb.name" . }}
    release: {{ .Release.Name | quote }}
  name: {{ template "mongodb.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
{{- end }}
