{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "mongodb.name" . }}
    release: {{ .Release.Name | quote }}
  name: {{ template "mongodb.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "mongodb.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "mongodb.fullname" . }}
{{- end }}
