apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.name" . }}
    release: {{ .Release.Name }}
spec:
  ports:
    - name: exporter
      protocol: TCP
      port: {{ .Values.prometheus.exporter.port }}
      targetPort: exporter
  selector:
    app: {{ template "mongodb.name" . }}
    release: {{ .Release.Name }}
