{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "mongodb.name" . }}
    release: {{ .Release.Name | quote }}
  name: {{ template "mongodb.serviceAccountName" . }}
{{- end }}
