source 'https://rubygems.org'

gem 'rails',        '4.1.5'
gem 'sass-rails',   '~> 4.0.3'
gem 'slim-rails',   '~> 2.1.5'
gem 'uglifier',     '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails', '~> 3.1.0'
gem 'turbolinks',   '~> 2.3.0'
gem 'jbuilder',     '~> 2.0'
gem 'foundation-rails'
gem 'sdoc',         '~> 0.4.0', group: :doc
gem 'devise'

group :development do
  gem 'sqlite3',    '~> 1.3.9'
  gem 'spring',     '~> 1.1.3'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rspec-rails'
end

group :production do
  gem 'pg',             '0.17.1'
  gem 'rails_12factor', '0.0.2'
end
