---
- name: Setting vim
  hosts: all

  tasks:
  - name: Write .vimrc config
    template:
      src: ../template/.vimrc
      dest: "~{{ ansible_user }}/.vimrc"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      backup: yes
