apiVersion: v1
kind: Service
metadata:
  name: gitlab-nodeport
  namespace: gitlab
  labels:
    name: gitlab
spec:
  type: NodePort
  selector:
    name: gitlab
  ports:
    - name: ssh
      port: 22
      nodePort: 32022
    - name: http
      port: 80
      nodePort: 32080
    - name: https
      port: 443
      nodePort: 32443
