# Nginx
# VERSION   0.0.1

# Set nginx base image
FROM nginx

# File Author / Mainteiner
MAINTAINER  Login Viktor <batazor111@gmail.com>

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
