version: "3"

volumes:
  prometheus_data: {}
  influxdb_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.11.1
    container_name: prometheus
    restart: always
    ports:
    - 9090:9090
    volumes:
    - ./prometheus/:/etc/prometheus/
    - prometheus_data:/prometheus

  influxdb:
    image: influxdb:1.7-alpine
    container_name: influxdb
    ports:
    - 8083:8083
    - 8086:8086
    - 8090:8090
    environment:
      INFLUXDB_DATA_ENGINE: tsm1
      INFLUXDB_REPORTING_DISABLED: "false"
    volumes:
    - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:5.4.4
    container_name: grafana
    ports:
    - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource"
