{
 "title": "GitLab KPI",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nickname",
    "query": "label_values(gitlab_issue_total, assigneeNickname)"
   },
   {
    "name": "milestoune",
    "query": "label_values(gitlab_issue_total, milestoune)"
   }
  ]
 },
 "panels": [
  {
   "title": "Issue max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(gitlab_issue_total{assigneeNickname=~\"$nickname\",milestoune=~\"$milestoune\"}) by (assigneeNickname)",
     "legendFormat": "{{assigneeNickname}}"
    }
   ]
  },
  {
   "title": "Avg issue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(gitlab_issue_total{assigneeNickname=~\"$nickname\",milestoune=~\"$milestoune\"}) by (assigneeNickname)"
    }
   ]
  },
  {
   "title": "Min Issue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(gitlab_issue_total{assigneeNickname=~\"$nickname\",milestoune=~\"$milestoune\"}) by (assigneeNickname)",
     "legendFormat": "{{assigneeNickname}}"
    }
   ]
  },
  {
   "title": "Issue total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "weight" }
   ],
   "targets": [
    {
     "expr": "gitlab_issue_total{assigneeNickname=~\"$nickname\",milestoune=~\"$milestoune\"}",
     "legendFormat": "{{assigneeNickname}} {{milestoune}}"
    }
   ]
  }
 ]
}