version: "3"

services:
  nodered:
    image: nodered/node-red-docker:slim-v10
    container_name: node-red
    privileged: true
    ports:
    - "1880:1880"
    # volumes:
    # - /data/nodered:/data
