nodeSelector: {}

annotations: {}

service:

  ## Annotations to be added to the Service
  ##
  annotations: {}

  ## Cluster-internal IP address for Alertmanager Service
  ##
  clusterIP: ""

  ## List of external IP addresses at which the Alertmanager Service will be available
  ##
  externalIPs: []

  ## External IP address to assign to Alertmanager Service
  ## Only used if service.type is 'LoadBalancer' and supported by cloud provider
  ##
  loadBalancerIP: ""

  ## List of client IPs allowed to access Alertmanager Service
  ## Only used if service.type is 'LoadBalancer' and supported by cloud provider
  ##
  loadBalancerSourceRanges: []

  ## Port to expose on each node
  ## Only used if service.type is 'NodePort'
  ##
  # nodePort: 30902

  ## Service type
  ##
  # type: NodePort

## Analytics frontend Docker image
##
image:
  repository: registry.gitlab.com/batazor/k8s-custom-metric
  tag: latest

storageSpec: {}
#   class: default
#   accessMode:
#   resources:
#     requests:
#       storage: 2Gi
#   selector: {}

resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 300m
    memory: 300Mi
