source 'https://rubygems.org'

gem 'rails',        '4.1.5'
gem 'sass-rails',   '~> 4.0.3'
gem 'slim-rails'
gem 'uglifier',     '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails', '~> 3.1.2'
gem 'turbolinks',   '~> 2.3.0'
gem 'jbuilder',     '~> 2.0'
gem 'redis'
gem 'sdoc',         '~> 0.4.0', group: :doc

group :development do
  gem 'sqlite3',    '~> 1.3.9'
  gem 'spring', '~> 1.7.0'
  gem 'rspec-rails'
end

group :production do
  gem 'unicorn'
  gem 'pg',             '0.17.1'
  gem 'rails_12factor', '0.0.2'
  gem 'resque'
end
