version: '2'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MYSQL_DATABASE=highloadcup
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
